USE invdbdb; -- same as in dockerfile

drop table if exists `books`;
CREATE TABLE `books` (
    `book_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(128) COLLATE utf8_bin NOT NULL DEFAULT '',
    `create_ts` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
    `update_ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`book_id`)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE = UTF8_UNICODE_CI;


drop table if exists `users`;
CREATE TABLE `users` (
    `user_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `email` VARCHAR(255) COLLATE utf8_bin NOT NULL DEFAULT '',
    `nickname` VARCHAR(32) COLLATE utf8_bin NOT NULL DEFAULT '',
    `password` VARCHAR(64) COLLATE UTF8_UNICODE_CI NOT NULL DEFAULT '',
    `verified` TINYINT(3) UNSIGNED NOT NULL DEFAULT 0,
    `admin` TINYINT(3) UNSIGNED NOT NULL DEFAULT 0,
    `create_ts` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
    `update_ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`user_id`),
    UNIQUE KEY (`email`),
    UNIQUE KEY (`nickname`)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE = UTF8_UNICODE_CI;

drop table if exists `ownerships`;
CREATE TABLE `ownerships` (
    `user_id` BIGINT(20) UNSIGNED NOT NULL,
    `book_id` BIGINT(20) UNSIGNED NOT NULL,
    `create_ts` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
    `update_ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`user_id`,`book_id`),
    FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE,
    FOREIGN KEY (`book_id`) REFERENCES `books` (`book_id`) ON DELETE CASCADE
)  ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE = UTF8_UNICODE_CI;
